config:
  clients:
    # Service name is monitoring-loki because Flux prefixes the Helm release name with the target namespace.
    - url: http://monitoring-loki.monitoring.svc.cluster.local:3100/loki/api/v1/push
