apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - serviceaccount.yaml
  - secretproviderclass.yaml
  - certificate.yaml
  - objectstore.yaml
  - cnpg-cluster.yaml
  - scheduled-backup.yaml
  - helmrepository.yaml
  - helmrelease.yaml
  - httproute.yaml
  - netpol-default-deny.yaml
  - netpol-allow-dns.yaml
  - netpol-allow-gateway-to-n8n.yaml
  - netpol-allow-n8n-to-db.yaml
  - netpol-allow-app-egress-https.yaml
  - netpol-allow-cnpg-egress-https.yaml
  - netpol-allow-cnpg-operator.yaml
configMapGenerator:
  - name: n8n-values
    namespace: acme
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml
